In [4]:
import torch #Pytorchをインポート
x=torch.tensor([1,2,3])#listを渡してTensorを生成
print(x)

tensor([1, 2, 3])


In [5]:
#listを入れ子にしてTensorを生成
x = torch.tensor([[1,2,3],[4,5,6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [6]:
x=torch.tensor([[1,2,3],[4,5,6]])
print(x.size())

torch.Size([2, 3])


In [7]:
x1 = torch.tensor([[1,2,3],[4,5,6]])
x2 = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float64)
x3 = torch.DoubleTensor([[1,2,3],[4,5,6]])
print(x1.dtype)
print(x2.dtype)
print(x3.dtype)

torch.int64
torch.float64
torch.float64


In [8]:
x = torch.arange(0,10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [9]:
x = torch.linspace(0,10,5)
print(x)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [10]:
x = torch.rand(2,3)
print(x)

tensor([[0.0158, 0.1623, 0.1538],
        [0.1582, 0.0243, 0.0721]])


In [11]:
x = torch.zeros(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
x = torch.ones(2,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [13]:
import numpy as np

In [14]:
array = np.array([[1,2,3],[4,5,6]])
print(array)

[[1 2 3]
 [4 5 6]]


In [15]:
tensor = torch.from_numpy(array)
print(tensor)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [16]:
tensor2array = tensor.numpy()
print(tensor2array)

[[1 2 3]
 [4 5 6]]


In [17]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x[1,2])

tensor(6)


In [18]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x[1,:])

tensor([4, 5, 6])


In [34]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x[0,:])

tensor([1, 2])


In [19]:
x = torch.tensor([[1,2,3],[4,5,6]])
x_reshape = x.view(3,2)
print(x)
print(x_reshape)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [20]:
x = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float64)
print(x+2)
print(x-2)
print(x*2)
print(x/2)

tensor([[3., 4., 5.],
        [6., 7., 8.]], dtype=torch.float64)
tensor([[-1.,  0.,  1.],
        [ 2.,  3.,  4.]], dtype=torch.float64)
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]], dtype=torch.float64)
tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]], dtype=torch.float64)


In [21]:
x = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float64)
y = torch.tensor([[4,5,6],[7,8,9]], dtype=torch.float64)
print(x+y)
print(x-y)
print(x*y)
print(x/y)

tensor([[ 5.,  7.,  9.],
        [11., 13., 15.]], dtype=torch.float64)
tensor([[-3., -3., -3.],
        [-3., -3., -3.]], dtype=torch.float64)
tensor([[ 4., 10., 18.],
        [28., 40., 54.]], dtype=torch.float64)
tensor([[0.2500, 0.4000, 0.5000],
        [0.5714, 0.6250, 0.6667]], dtype=torch.float64)


In [22]:
x = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float64)
print(torch.min(x))
print(torch.max(x))
print(torch.mean(x))
print(torch.sum(x))

tensor(1., dtype=torch.float64)
tensor(6., dtype=torch.float64)
tensor(3.5000, dtype=torch.float64)
tensor(21., dtype=torch.float64)


In [23]:
x = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float64)
print(torch.sum(x).item())

21.0


In [24]:
import torch
a = torch.tensor(3, requires_grad=True, dtype=torch.float64)
b = torch.tensor(4, requires_grad=True, dtype=torch.float64)
x = torch.tensor(5, requires_grad=True, dtype=torch.float64)

y = a*x+b
print(y)

tensor(19., dtype=torch.float64, grad_fn=<AddBackward0>)


In [25]:
y.backward()

In [26]:
print(a.grad)
print(b.grad)
print(x.grad)

tensor(5., dtype=torch.float64)
tensor(1., dtype=torch.float64)
tensor(3., dtype=torch.float64)
